package renderer

import (
	"fmt"
	"strings"

	"github.com/kwrkb/repo-hand-off/internal/collector"
)

// RenderHandoff generates HANDOFF.md content from a snapshot.
func RenderHandoff(s *collector.Snapshot) string {
	var b strings.Builder

	b.WriteString("# HANDOFF.md\n")
	b.WriteString(fmt.Sprintf("> Generated by repo-hand-off at %s\n\n", s.Timestamp.Format("2006-01-02 15:04:05")))

	// Project section
	b.WriteString("## Project\n")
	if s.Git.RemoteURL != "" {
		b.WriteString(fmt.Sprintf("- Repository: %s\n", s.Git.RemoteURL))
	}
	b.WriteString(fmt.Sprintf("- Branch: %s @ %s\n", s.Git.Branch, s.Git.ShortHash))
	if s.Git.HasChanges {
		b.WriteString("- Uncommitted changes: yes\n")
	} else {
		b.WriteString("- Uncommitted changes: no\n")
	}
	b.WriteString("\n")

	// Vision
	b.WriteString("## Vision\n")
	writeContentOrNotFound(&b, s.Files.Vision)

	// Plan
	b.WriteString("## Plan\n")
	writeContentOrNotFound(&b, s.Files.Plan)

	// Lessons
	b.WriteString("## Lessons\n")
	writeContentOrNotFound(&b, s.Files.Lessons)

	// Current State
	b.WriteString("## Current State\n")
	if len(s.RecentLogs) > 0 {
		b.WriteString("### Recent Commits\n")
		for _, log := range s.RecentLogs {
			b.WriteString(fmt.Sprintf("- %s\n", log))
		}
		b.WriteString("\n")
	}
	if s.Git.DiffSummary != "" {
		b.WriteString("### Uncommitted Changes\n")
		b.WriteString("```\n")
		b.WriteString(s.Git.DiffSummary)
		b.WriteString("\n```\n\n")
	}

	// Directory Structure
	b.WriteString("## Directory Structure\n")
	b.WriteString("```\n")
	b.WriteString(s.DirTree)
	b.WriteString("\n```\n")

	return b.String()
}

func writeContentOrNotFound(b *strings.Builder, content string) {
	if content == "" {
		b.WriteString("Not found.\n\n")
	} else {
		b.WriteString(content)
		if !strings.HasSuffix(content, "\n") {
			b.WriteString("\n")
		}
		b.WriteString("\n")
	}
}
