package parser

import (
	"testing"
)

func TestParseHandoffMarkdown(t *testing.T) {
	content := `# HANDOFF.md
> Generated by repo-hand-off at 2026-03-20 12:00:00

## Project
- Branch: main @ abc1234

## Vision
# Vision
Build something great.

## Plan
# Plan
Step 1: Do it.

## Lessons
Some lessons learned.

## Current State
### Recent Commits
- abc1234 initial commit

## Directory Structure
` + "```\nrepo/\n├── main.go\n```\n"

	parsed, err := ParseHandoffMarkdown(content)
	if err != nil {
		t.Fatalf("ParseHandoffMarkdown failed: %v", err)
	}

	if parsed.Vision != "# Vision\nBuild something great." {
		t.Errorf("Vision = %q", parsed.Vision)
	}
	if parsed.Plan != "# Plan\nStep 1: Do it." {
		t.Errorf("Plan = %q", parsed.Plan)
	}
	if parsed.Lessons != "Some lessons learned." {
		t.Errorf("Lessons = %q", parsed.Lessons)
	}
}

func TestParseHandoffMissingSections(t *testing.T) {
	content := `# HANDOFF.md

## Vision
# Vision
Build something great.

## Directory Structure
` + "```\nrepo/\n```\n"

	parsed, err := ParseHandoffMarkdown(content)
	if err != nil {
		t.Fatalf("ParseHandoffMarkdown failed: %v", err)
	}

	if parsed.Vision == "" {
		t.Error("Vision should not be empty")
	}
	if parsed.Plan != "" {
		t.Errorf("Plan should be empty, got %q", parsed.Plan)
	}
	if parsed.Lessons != "" {
		t.Errorf("Lessons should be empty, got %q", parsed.Lessons)
	}
}

func TestParseHandoffNotFound(t *testing.T) {
	content := `# HANDOFF.md

## Vision
# Vision
Build something great.

## Plan
Not found.

## Lessons
Not found.
`

	parsed, err := ParseHandoffMarkdown(content)
	if err != nil {
		t.Fatalf("ParseHandoffMarkdown failed: %v", err)
	}

	if parsed.Plan != "" {
		t.Errorf("Plan should be empty for 'Not found.', got %q", parsed.Plan)
	}
	if parsed.Lessons != "" {
		t.Errorf("Lessons should be empty for 'Not found.', got %q", parsed.Lessons)
	}
}
